In [2]:
import pandas as pd
import numpy as np # Used for mathematical operations
import os # Added for file existence checks

In [3]:
# Task 3: Generate Analysed Data
# This step creates a dummy data/trends_analysed.csv file. In a real-world scenario, this would involve loading raw data, performing analysis, and transforming it into the format expected by the visualization functions.

In [4]:
def analyze_data():
    input_file = "data/trends_clean.csv"

    # 1. Check if the clean data exists before trying to read it
    if not os.path.exists(input_file):
        print("Clean data not found. Run Task 2 first!")
        return # Exit the function if the file doesn't exist

    print(f"Loading {input_file} for analysis...")
    # 2. Load the cleaned CSV into a Pandas DataFrame
    df = pd.read_csv(input_file)

    # 3. Add a new column: 'title_length'
    # Calculates the number of characters in the post title
    df['title_length'] = df['title'].apply(len)

    # 4. Add a new column: 'engagement_score'
    # Adding num_comments and score. We use np.where to prevent division by zero,
    # but here a simple addition or log scale works well. Let's do a NumPy logarithm
    # of the score to normalize highly skewed upvote counts.
    # np.log1p computes log(1 + x) safely even if x is 0.
    df['log_score'] = np.log1p(df['score'])

    # 5. Add a new column categorizing the post using NumPy's 'where' function
    # If the score is above the median score, label it 'High Virality', otherwise 'Normal'
    median_score = np.median(df['score'])
    df['virality'] = np.where(df['score'] > median_score, 'High Virality', 'Normal')

    # 6. Print a quick summary to the console to prove the analysis worked
    print("\n--- Analysis Summary ---")
    print(f"Average Score: {np.mean(df['score']):.2f}")
    print(f"Top Subreddit: {df['subreddit'].value_counts().idxmax()}")

    # 7. Save the newly analyzed data to a final CSV
    output_file = "data/trends_analysed.csv"
    df.to_csv(output_file, index=False)
    print(f"\nAnalysis complete. Saved to {output_file}")

analyze_data() # Call the function to execute the analysis

Clean data not found. Run Task 2 first!

In [5]:
import os

file_path = "data/trends_analysed.csv"
if os.path.exists(file_path):
    print(f"The file '{file_path}' exists.")
else:
    print(f"The file '{file_path}' does not exist.")

The file 'data/trends_analysed.csv' does not exist.

In [5]:
import numpy as np
import pandas as pd # Added pandas import to read CSV

# Load the analyzed data from the previous step
input_file_path = "data/trends_analysed.csv"
df_analyzed = None # Initialize df_analyzed to None

try:
    df_analyzed = pd.read_csv(input_file_path)
    print(f"Loaded {input_file_path} for advanced analysis.")
except FileNotFoundError:
    print(f"Error: {input_file_path} not found. Please ensure the analysis step (Task 2/analyze_data function) has been executed.")
    # Removed exit() as it didn't fully prevent NameError in Colab's interactive execution.
    # The 'if df_analyzed is not None:' block below will handle prevention of NameError.

if df_analyzed is not None:
    # Task 3: Advanced Analysis with NumPy/Pandas

    # 1. Calculate a 'Total Engagement' metric (Score + Comments)
    # Original code used 'df_cleaned' and 'num_comments' which are not available.
    # Using 'score' for engagement as 'num_comments' column is not in trends_analysed.csv.
    df_analyzed['engagement'] = df_analyzed['score']

    # 2. Use NumPy to find the overall mean and standard deviation of scores
    mean_score = np.mean(df_analyzed['score'])
    std_score = np.std(df_analyzed['score'])

    # 3. Identify the 'Viral' stories (scores higher than mean + 1 std dev)
    viral_stories = df_analyzed[df_analyzed['score'] > (mean_score + std_score)]

    # 4. Find the top story for each category
    # Original code used 'category' which is not available.
    # Using 'virality' as it's created by the 'analyze_data' function and represents a category.
    top_per_category = df_analyzed.sort_values('score', ascending=False).groupby('virality').head(1)

    print(f'Average Score: {mean_score:.2f}')
    print(f'Number of Viral Stories: {len(viral_stories)}')
    print('\nTop Story per Category:')
    # Original code used 'category' and 'author' which are not available.
    # Displaying 'virality', 'title', 'score' instead.
    display(top_per_category[['virality', 'title', 'score']])

Error: data/trends_analysed.csv not found. Please ensure the analysis step (Task 2/analyze_data function) has been executed.

In [4]:
import pandas as pd
import numpy as np
import os
import json

# Create the 'data' directory if it doesn't exist
if not os.path.exists('data'):
    os.makedirs('data')
    print("Created directory: 'data'")
else:
    print("Directory 'data' already exists.")

Directory 'data' already exists.

### Generating a dummy `data/trends_clean.csv`

Since `data/trends_clean.csv` (from Task 2) is not available, I will create a dummy file with example data to proceed with Task 3.

In [12]:
import pandas as pd
import numpy as np
import os

# Create the 'data' directory if it doesn't exist
if not os.path.exists('data'):
    os.makedirs('data')
    print("Created directory: 'data'")

# Dummy data for trends_clean.csv
dummy_data = {
    'post_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    'title': [
        'AI model beats humans at coding',
        'New discovery in quantum physics',
        'Top 10 new gadgets of the year',
        'Understanding machine learning basics',
        'How to build a custom PC',
        'Future of renewable energy',
        'The latest in space exploration',
        'Breakthrough in medical research',
        'Best programming languages for 2024',
        'Electric cars are the future',
        'Blockchain technology explained',
        'Impact of AI on daily life',
        'History of the internet',
        'Cybersecurity tips for beginners',
        'Why learn Python?'
    ],
    'category': [
        'technology', 'science', 'technology', 'technology', 'technology',
        'science', 'science', 'science', 'technology', 'technology',
        'technology', 'technology', 'technology', 'technology', 'technology'
    ],
    'score': [
        87432, 15678, 23456, 12345, 9876, 18765, 34567, 21098, 11234, 14567,
        7890, 19876, 6543, 8765, 10000
    ],
    'num_comments': [
        4891, 789, 1234, 567, 321, 987, 1567, 1123, 456, 678,
        234, 1000, 200, 300, 400
    ],
    'subreddit': [
        'r/technology', 'r/science', 'r/gadgets', 'r/machinelearning', 'r/buildapc',
        'r/energy', 'r/space', 'r/medicine', 'r/programming', 'r/electricvehicles',
        'r/blockchain', 'r/futurology', 'r/history', 'r/cybersecurity', 'r/learnpython'
    ]
}

df_clean_dummy = pd.DataFrame(dummy_data)

output_clean_file = "data/trends_clean.csv"
df_clean_dummy.to_csv(output_clean_file, index=False)
print(f"Dummy '{output_clean_file}' created successfully with {len(df_clean_dummy)} rows.")

Dummy 'data/trends_clean.csv' created successfully with 15 rows.

## Task 3 — Analysis with Pandas & NumPy

### 1 — Load and Explore

In [13]:
import pandas as pd
import numpy as np
import os

# Load data/trends_clean.csv into a Pandas DataFrame
input_file = "data/trends_clean.csv"
if not os.path.exists(input_file):
    print(f"Error: {input_file} not found. Please ensure Task 2 is completed.")
else:
    df = pd.read_csv(input_file)
    print(f"Loaded {input_file}.")

    # Print the first 5 rows
    print("\nFirst 5 rows:")
    display(df.head())

    # Print the shape of the DataFrame (rows and columns)
    print(f"\nLoaded data: {df.shape}")

    # Print the average score and average num_comments across all stories
    avg_score = df['score'].mean()
    avg_num_comments = df['num_comments'].mean()
    print(f"\nAverage score   : {avg_score:,.0f}")
    print(f"Average comments: {avg_num_comments:,.0f}")

Loaded data/trends_clean.csv.

First 5 rows:

,post_id,title,category,score,num_comments,subreddit
0,1,AI model beats humans at coding,technology,87432,4891,r/technology
1,2,New discovery in quantum physics,science,15678,789,r/science
2,3,Top 10 new gadgets of the year,technology,23456,1234,r/gadgets
3,4,Understanding machine learning basics,technology,12345,567,r/machinelearning
4,5,How to build a custom PC,technology,9876,321,r/buildapc

Loaded data: (15, 6)

Average score   : 20,139
Average comments: 983

### 2 — Basic Analysis with NumPy

In [14]:
if 'df' in locals() and df is not None:
    print("\n--- NumPy Stats ---")

    # Mean, median, and standard deviation of score
    mean_score_np = np.mean(df['score'])
    median_score_np = np.median(df['score'])
    std_dev_score_np = np.std(df['score'])
    print(f"Mean score   : {mean_score_np:,.0f}")
    print(f"Median score : {median_score_np:,.0f}")
    print(f"Std deviation: {std_dev_score_np:,.0f}")

    # Highest score and lowest score
    max_score_np = np.max(df['score'])
    min_score_np = np.min(df['score'])
    print(f"Max score    : {max_score_np:,.0f}")
    print(f"Min score    : {min_score_np:,.0f}")

    # Which category has the most stories?
    most_stories_category = df['category'].value_counts().idxmax()
    num_stories_in_category = df['category'].value_counts().max()
    print(f"\nMost stories in: {most_stories_category} ({num_stories_in_category} stories)")

    # Which story has the most comments? Print its title and comment count.
    most_comments_story = df.loc[df['num_comments'].idxmax()]
    print(f"\nMost commented story: \"{most_comments_story['title']}\"  — {most_comments_story['num_comments']:,} comments")
else:
    print("DataFrame 'df' not found. Please run the 'Load and Explore' step first.")

--- NumPy Stats ---
Mean score   : 20,139
Median score : 14,567
Std deviation: 19,346
Max score    : 87,432
Min score    : 6,543

Most stories in: technology (11 stories)

Most commented story: "AI model beats humans at coding"  — 4,891 comments

### 3 — Add New Columns

In [15]:
if 'df' in locals() and df is not None:
    # Add engagement column: num_comments / (score + 1)
    df['engagement'] = df['num_comments'] / (df['score'] + 1)
    print("Added 'engagement' column.")

    # Add is_popular column: True if score > average score, else False
    # Recalculate average score to ensure it's based on current df state if this cell is run independently
    current_avg_score = df['score'].mean()
    df['is_popular'] = df['score'] > current_avg_score
    print(f"Added 'is_popular' column (based on average score of {current_avg_score:,.0f}).")

    print("\nDataFrame with new columns (first 5 rows):")
    display(df.head())
else:
    print("DataFrame 'df' not found. Please run the 'Load and Explore' step first.")

Added 'engagement' column.
Added 'is_popular' column (based on average score of 20,139).

DataFrame with new columns (first 5 rows):

,post_id,title,category,score,num_comments,subreddit,engagement,is_popular
0,1,AI model beats humans at coding,technology,87432,4891,r/technology,0.055940,True
1,2,New discovery in quantum physics,science,15678,789,r/science,0.050322,False
2,3,Top 10 new gadgets of the year,technology,23456,1234,r/gadgets,0.052607,True
3,4,Understanding machine learning basics,technology,12345,567,r/machinelearning,0.045926,False
4,5,How to build a custom PC,technology,9876,321,r/buildapc,0.032500,False

### 4 — Save the Result

In [17]:
if 'df' in locals() and df is not None:
    output_analysed_file = "data/trends_analysed.csv"
    df.to_csv(output_analysed_file, index=False)
    print(f"Saved to {output_analysed_file}")
else:
    print("DataFrame 'df' not found. Cannot save. Please run the previous steps first.")

Saved to data/trends_analysed.csv